(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],mix=a=>{a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a},safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paras=[
'Oncosalud es una organización especializada en oncología y programas oncológicos. Su propósito no se limita a atender a una persona cuando ya tiene cáncer. La organización busca prevenir la enfermedad, detectarla oportunamente, diagnosticarla y tratarla eficientemente, cuidar al paciente durante su recuperación y contribuir a preservar su calidad de vida.',
'Para ello dispone de programas oncológicos con diferentes condiciones de cobertura. Algunos programas incluyen chequeos oncológicos, fase diagnóstica y cobertura para tratamientos como quimioterapia y radioterapia.',
'En la etapa asistencial, Oncosalud dispone de servicios de detección y diagnóstico, tratamiento mediante radioterapia, cirugía oncológica y quimioterapia, además de servicios complementarios y cuidados en casa. Sus unidades de tratamiento cuentan con profesionales especializados y tecnología orientada a la atención del cáncer.',
'Cuando un afiliado obtiene un diagnóstico oncológico positivo debe activar su programa. Para ello presenta, entre otros documentos, el diagnóstico anatomopatológico y los exámenes auxiliares relacionados con el diagnóstico. Durante la activación se realizan validaciones administrativas, se brinda orientación al paciente, se asigna un médico tratante y posteriormente un ejecutivo de acompañamiento.',
'Consideremos el caso de María, de 48 años, quien se encuentra afiliada desde hace varios años a uno de los programas oncológicos de Oncosalud.',
'Durante un examen médico se identifica una lesión sospechosa. Después de realizar los estudios correspondientes, una biopsia confirma un diagnóstico de cáncer.',
'María comunica su diagnóstico a Oncosalud y presenta el informe anatomopatológico, exámenes de laboratorio, imágenes y demás documentos requeridos. Después de revisar esta información se activa su programa y se le asigna un médico tratante.',
'El equipo médico estudia la condición de María, analiza sus antecedentes y resultados clínicos y establece un plan terapéutico. De acuerdo con las características particulares de la enfermedad, el tratamiento requiere intervenciones coordinadas entre diferentes especialistas.',
'Durante los siguientes meses se ejecutan las terapias indicadas y se realizan controles para conocer la evolución de la paciente, identificar posibles efectos adversos y determinar si es necesario continuar, modificar o concluir determinadas intervenciones.',
'Paralelamente, María recibe orientación durante su atención y posteriormente continúa bajo seguimiento.',
'Esta atención no se desarrolla de manera aislada. Para hacerla posible, Oncosalud necesita profesionales especializados, sistemas de información, medicamentos e insumos, infraestructura y equipamiento, administración financiera, proveedores y mecanismos destinados a asegurar la calidad y seguridad del paciente.',
'Además, la organización desarrolla actividades vinculadas con conocimiento científico, investigación y actualización de prácticas clínicas para apoyar el diagnóstico y tratamiento de enfermedades oncológicas.',
'A partir de esta información, asume el rol de analista de procesos de Oncosalud y toma las siguientes decisiones.'
];
const option=(text,correct,feedback)=>({text,correct,feedback});
const questions=[
{key:'value',step:1,section:1,title:'DECISIÓN 1 — ¿QUÉ VALORA REALMENTE EL CLIENTE?',q:'Considerando que una propuesta de valor representa el beneficio diferencial que el cliente reconoce y no solamente una característica de la organización, ¿cuál de las siguientes alternativas representa mejor la propuesta de valor principal de Oncosalud?',max:4,good:'Correcto. Has identificado el beneficio principal que recibe el cliente. La infraestructura, los profesionales y la tecnología contribuyen a generar valor, pero la propuesta de valor expresa el beneficio integral que finalmente percibe el paciente.',options:[option('Proporcionar instalaciones modernas y tecnologías avanzadas para realizar procedimientos médicos especializados.',0,'La tecnología y la infraestructura son recursos que permiten generar valor, pero no constituyen por sí mismas el beneficio principal que recibe el paciente.'),option('Ofrecer programas oncológicos caracterizados principalmente por tener precios accesibles y diferentes alternativas de pago.',0,'El precio puede influir en la decisión del cliente, pero la diferenciación principal está relacionada con la protección y atención oncológica especializada.'),option('Brindar protección integral y especializada frente al cáncer, acompañando a la persona desde la prevención y detección hasta el diagnóstico, tratamiento y continuidad de su cuidado.',1,''),option('Contar con médicos especialistas, investigadores y profesionales permanentemente capacitados en oncología.',0,'Los profesionales especializados son una capacidad esencial, pero la propuesta de valor debe expresarse desde el beneficio recibido por el cliente.'),option('Incrementar la cantidad de programas de salud disponibles para atender diferentes segmentos del mercado.',0,'Incrementar el portafolio puede ser una estrategia comercial, pero no expresa el beneficio diferencial principal que recibe el paciente.')]},
{key:'key',step:2,section:2,title:'DECISIÓN 2 — DEL VALOR AL PROCESO',q:'Considerando el caso de María, ¿cuál de los siguientes procesos aporta de manera más directa y decisiva a la materialización de la propuesta de valor identificada?',max:4,good:'Correcto. Este proceso transforma el diagnóstico y la información clínica en una intervención terapéutica especializada que recibe directamente el paciente.',options:[option('Gestión financiera y administrativa.',0,'La gestión financiera sostiene las operaciones, pero no entrega directamente el tratamiento.'),option('Gestión de tecnologías de información.',0,'La tecnología habilita la prestación asistencial, pero funciona principalmente como soporte.'),option('Gestión del tratamiento oncológico especializado.',1,''),option('Gestión de proveedores y terceros.',0,'Los proveedores suministran recursos, pero no materializan directamente el beneficio principal.'),option('Gestión de comunicaciones y marketing.',0,'La comunicación informa y capta usuarios, pero no produce directamente el tratamiento.')]},
{key:'supplier',step:3,section:3,title:'DECISIÓN 3 — ANALIZA EL PROCESO MEDIANTE SIPOC',q:'¿Quién suministra una de las principales entradas clínicas requeridas para desarrollar el tratamiento?',max:2,correct:'Equipo de diagnóstico y servicios de apoyo diagnóstico.',bad:'Recuerda que el Supplier es quien proporciona una entrada necesaria. Identifica quién entrega el diagnóstico y los resultados clínicos.',options:['Área de marketing.','Paciente dado de alta.','Equipo de diagnóstico y servicios de apoyo diagnóstico.','Proceso de seguimiento posterior al tratamiento.']},
{key:'input',step:3,section:3,title:'DECISIÓN 3 — ANALIZA EL PROCESO MEDIANTE SIPOC',q:'¿Cuál representa mejor las entradas principales del proceso?',max:2,correct:'Diagnóstico confirmado, historia clínica, resultados de exámenes e información necesaria del paciente.',bad:'Una entrada existe antes de la transformación y es utilizada por el proceso. Revisa qué información clínica necesita el equipo.',options:['Campañas publicitarias, tarifas comerciales y publicaciones digitales.','Diagnóstico confirmado, historia clínica, resultados de exámenes e información necesaria del paciente.','Tratamiento finalizado y evaluación de respuesta terapéutica.','Reporte financiero anual y presupuesto institucional.']},
{key:'output',step:3,section:3,title:'DECISIÓN 3 — ANALIZA EL PROCESO MEDIANTE SIPOC',q:'¿Cuál representa mejor el Output principal del proceso?',max:2,correct:'Tratamiento oncológico especializado ejecutado y monitoreado de acuerdo con las necesidades clínicas del paciente.',bad:'El Output es aquello que el proceso genera. La curación no puede garantizarse y el diagnóstico corresponde a una entrada.',options:['Paciente necesariamente curado del cáncer.','Medicamentos almacenados y equipos médicos disponibles.','Tratamiento oncológico especializado ejecutado y monitoreado de acuerdo con las necesidades clínicas del paciente.','Diagnóstico anatomopatológico confirmado.']},
{key:'customer',step:3,section:3,title:'DECISIÓN 3 — ANALIZA EL PROCESO MEDIANTE SIPOC',q:'¿Quién es el Customer principal del proceso?',max:2,correct:'Paciente oncológico.',bad:'El Customer es quien recibe directamente el producto o resultado generado por el proceso.',options:['Proveedor de medicamentos.','Área de finanzas.','Paciente oncológico.','Empresa de tecnología.']}
];
const processes=[['it','Gestión de tecnologías de información','support'],['pre','Gestión de prevención y detección temprana','mission'],['quality','Gestión de calidad y seguridad del paciente','strategic'],['follow','Gestión del seguimiento y continuidad del cuidado','mission'],['log','Gestión de abastecimiento y logística','support'],['gov','Gestión estratégica y gobierno','strategic'],['treat','Gestión del tratamiento oncológico especializado','mission'],['talent','Gestión del talento humano','support'],['innov','Gestión de innovación y conocimiento científico','strategic']],labels={strategic:'Estratégicos',mission:'Misionales',support:'Soporte'},stepLabels=['Caso','Propuesta de valor','Proceso clave','SIPOC','Mapa de procesos','Resultados'];
let data,index,selected,assign,dragged,locked;
function resetData(){data={name:'',answers:{},scores:{value:0,key:0,sipoc:0,map:0},total:0,percentage:0};index=0;selected=null;assign={};locked=false}
function progress(n){$('#progress').innerHTML=stepLabels.map((x,i)=>`<li class="${i<n?'done':i===n?'active':''}" ${i===n?'aria-current="step"':''}>${x}</li>`).join('')}
function show(id,n){$$('.screen').forEach(x=>x.hidden=true);$(id).hidden=false;if(n!==undefined)progress(n);window.scrollTo({top:0,behavior:'smooth'})}
function renderQuestion(){let q=questions[index];selected=null;locked=false;show('#questionScreen',q.section);$('#qStep').textContent=`Decisión ${q.step}${q.step===3?` · Pregunta ${index-1} de 4`:''}`;$('#qTitle').textContent=q.title;$('#qText').textContent=q.q;$('#qExtra').innerHTML=q.step===3?'<div class="process"><strong>Proceso analizado:</strong><br>GESTIÓN DEL TRATAMIENTO ONCOLÓGICO ESPECIALIZADO</div><p>SIPOC: <strong>Supplier → Input → Process → Output → Customer</strong></p>':'';let opts=q.options.map((o,i)=>typeof o==='string'?{text:o,id:i}:{...o,id:i});$('#options').innerHTML=mix(opts).map(o=>`<label class="opt"><input type="radio" name="answer" value="${o.id}"><span>${safe(o.text)}</span></label>`).join('');$('#feedback').innerHTML='';$('#confirm').hidden=false;$('#confirm').disabled=true;$('#next').hidden=true;$$('.opt input').forEach(i=>i.onchange=e=>{selected=+e.target.value;$$('.opt').forEach(o=>o.classList.toggle('selected',o.querySelector('input').checked));$('#confirm').disabled=false})}
function evaluate(){if(selected===null||locked)return;locked=true;let q=questions[index],choice=q.options[selected],text=typeof choice==='string'?choice:choice.text,ok=q.correct?text===q.correct:!!choice.correct,points=ok?q.max:0,feedback=ok?(q.good||`Correcto. Has identificado adecuadamente el componente ${q.key}.`):(q.bad||choice.feedback),correct=q.correct||q.options.find(x=>x.correct).text;data.answers[q.key]={answer:text,correct:ok,points,feedback,correctAnswer:correct};if(q.step===3)data.scores.sipoc+=points;else data.scores[q.key]=points;$$('.opt input').forEach(i=>i.disabled=true);$('#confirm').hidden=true;$('#next').hidden=false;$('#feedback').innerHTML=`<div class="feedback ${ok?'ok':'bad'}"><strong>${ok?'Respuesta correcta':'Respuesta incorrecta'} · ${points?'+'+points:'0'} puntos</strong>${safe(feedback)}</div>`}
function next(){if(index<questions.length-1){index++;renderQuestion()}else showSipoc()}
function showSipoc(){let nodes=[['SUPPLIER','Equipo de diagnóstico y servicios de apoyo diagnóstico'],['INPUT','Diagnóstico confirmado + historia clínica + resultados de exámenes + información del paciente'],['PROCESS','Gestión del tratamiento oncológico especializado'],['OUTPUT','Tratamiento oncológico especializado ejecutado y monitoreado'],['CUSTOMER','Paciente oncológico']];$('#qStep').textContent='Decisión 3 completada';$('#qTitle').textContent='SIPOC CONSTRUIDO';$('#qText').textContent='Observa cómo los cinco componentes describen el proceso.';$('#qExtra').innerHTML='';$('#options').innerHTML=`<div class="flow" role="img" aria-label="Diagrama SIPOC">${nodes.map((n,i)=>`${i?'<div class="arrow">→</div>':''}<div class="node"><b>${n[0]}</b>${n[1]}</div>`).join('')}</div>`;$('#feedback').innerHTML='';$('#confirm').hidden=true;$('#next').hidden=false;$('#next').textContent='CONTINUAR AL MAPA DE PROCESOS';$('#next').onclick=()=>{renderMap();$('#next').onclick=next}}
function card(p){return `<article id="p-${p[0]}" class="item" draggable="true" data-id="${p[0]}"><p>${p[1]}</p><label class="sr" for="s-${p[0]}">Categoría para ${p[1]}</label><select id="s-${p[0]}" data-id="${p[0]}"><option value="">Seleccionar categoría</option><option value="strategic">Estratégico</option><option value="mission">Misional</option><option value="support">Soporte</option></select></article>`}
function renderMap(){assign={};locked=false;show('#mapScreen',4);$('#zones').innerHTML=Object.entries(labels).map(([k,v])=>`<section class="zone" data-cat="${k}"><h3>${v.toUpperCase()}</h3><div></div></section>`).join('');$('#pool').innerHTML=mix(processes).map(card).join('');$('#mapFeedback').innerHTML='';$('#validate').hidden=false;$('#validate').disabled=true;$('#seeResults').hidden=true;$$('.item').forEach(x=>{x.ondragstart=()=>dragged=x.dataset.id;x.querySelector('select').onchange=e=>place(e.target.dataset.id,e.target.value)});$$('.zone').forEach(z=>{z.ondragover=e=>{e.preventDefault();z.classList.add('over')};z.ondragleave=()=>z.classList.remove('over');z.ondrop=e=>{e.preventDefault();z.classList.remove('over');place(dragged,z.dataset.cat)}})}
function place(id,cat){if(locked||!id)return;if(cat)assign[id]=cat;else delete assign[id];let el=$(`#p-${id}`);el.querySelector('select').value=cat;(cat?$(`.zone[data-cat="${cat}"]>div`):$('#pool')).appendChild(el);let n=Object.keys(assign).length;$('#count').textContent=`Procesos clasificados: ${n} / 9`;$('#validate').disabled=n!==9}
function validateMap(){if(Object.keys(assign).length<9)return;locked=true;let count=0,errors={strategic:0,mission:0,support:0},details=processes.map(p=>{let ok=assign[p[0]]===p[2];if(ok)count++;else errors[p[2]]=1;return{name:p[1],answer:labels[assign[p[0]]],correct:ok,correctCategory:labels[p[2]]}});data.scores.map=count;data.answers.map={correct:count===9,points:count,count,details};$$('.item select').forEach(s=>s.disabled=true);$$('.item').forEach(x=>x.draggable=false);let notes=[];if(errors.strategic)notes.push('Los procesos estratégicos orientan, gobiernan, controlan o desarrollan capacidades de largo plazo.');if(errors.mission)notes.push('Los procesos misionales participan directamente en la cadena que entrega valor al cliente.');if(errors.support)notes.push('Los procesos de soporte proporcionan personas, tecnología, materiales, infraestructura u otros recursos.');$('#mapFeedback').innerHTML=`<div class="feedback ${count===9?'ok':''}"><strong>${count} de 9 correctamente clasificados · +${count} puntos</strong>${notes.map(x=>`<p>${x}</p>`).join('')}</div><div class="correct-map"><div class="band"><b>PROCESOS ESTRATÉGICOS</b><span>Gestión estratégica y gobierno</span><span>Gestión de calidad y seguridad del paciente</span><span>Gestión de innovación y conocimiento científico</span></div><div class="band"><b>PROCESOS MISIONALES</b><span>Prevención y detección temprana → Tratamiento oncológico especializado → Seguimiento y continuidad del cuidado</span></div><div class="band"><b>PROCESOS DE SOPORTE</b><span>Tecnologías de información · Abastecimiento y logística · Talento humano</span></div></div>`;$('#validate').hidden=true;$('#seeResults').hidden=false}
function reportRows(){let rows=[['Propuesta de valor','value',4],['Proceso clave','key',4],['Supplier','supplier',2],['Input','input',2],['Output','output',2],['Customer','customer',2]].map(([l,k,m])=>{let a=data.answers[k];return `<tr><td><b>${l}</b></td><td>${safe(a.answer)}${a.correct?'':`<br><small><b>Respuesta esperada:</b> ${safe(a.correctAnswer)}</small>`}</td><td class="${a.correct?'yes':'no'}">${a.correct?'✓ Correcto':'✗ Incorrecto'}</td><td>${a.points} / ${m}</td><td>${safe(a.feedback)}</td></tr>`});let m=data.answers.map;rows.push(`<tr><td><b>Clasificación de procesos</b></td><td>${m.count} de 9 correctamente clasificados.${m.details.filter(x=>!x.correct).map(x=>`<br><small>${safe(x.name)}: ${safe(x.answer)} → ${safe(x.correctCategory)}</small>`).join('')}</td><td class="${m.correct?'yes':'no'}">${m.correct?'✓ Correcto':'✗ Requiere revisión'}</td><td>${m.points} / 9</td><td>${m.correct?'Has diferenciado correctamente los tipos de proceso.':'Revisa dirección, cadena de valor y provisión de recursos.'}</td></tr>`);return rows.join('')}
function finalAnalysis(){let a=data.answers,o=[];if(data.total===25)return '<p>Excelente trabajo. Has relacionado correctamente propuesta de valor, cadena de valor, SIPOC y arquitectura de procesos. Esto demuestra que comprendes que la gestión por procesos parte del valor entregado al cliente y no del organigrama.</p>';if(!a.value.correct)o.push('Refuerza la diferencia entre una propuesta de valor y los recursos utilizados para producirla. La propuesta se formula desde el beneficio que percibe el cliente.');if(!a.key.correct)o.push('Revisa la relación entre propuesta de valor y procesos misionales. Un proceso clave produce directamente el beneficio.');if(!a.supplier.correct||!a.input.correct)o.push('Conviene reforzar la parte inicial del SIPOC: Supplier proporciona; Input es lo que el proceso recibe y transforma.');if(!a.output.correct||!a.customer.correct)o.push('Revisa la parte final del SIPOC: Output es el resultado; Customer es quien lo recibe.');let m=a.map.details;if(m.some(x=>!x.correct&&x.correctCategory==='Estratégicos'))o.push('Refuerza la finalidad de los procesos estratégicos: orientar, gobernar y controlar.');if(m.some(x=>!x.correct&&x.correctCategory==='Misionales'))o.push('Refuerza la cadena de valor: los procesos misionales entregan directamente valor al cliente.');if(m.some(x=>!x.correct&&x.correctCategory==='Soporte'))o.push('Los procesos de soporte proporcionan recursos y capacidades a los procesos misionales.');return `<ul>${o.map(x=>`<li>${x}</li>`).join('')}</ul>`}
function results(){data.total=Object.values(data.scores).reduce((a,b)=>a+b,0);data.percentage=Math.round(data.total/25*100);let level=data.total>=22?'DOMINIO SATISFACTORIO':data.total>=18?'COMPRENSIÓN ADECUADA':data.total>=14?'COMPRENSIÓN PARCIAL':'REQUIERE REFORZAMIENTO';show('#results',5);$('#date').textContent='Fecha y hora de finalización: '+new Date().toLocaleString('es-PE');$('#rName').textContent=data.name;$('#rScore').textContent=`${data.total} / 25`;$('#rPercent').textContent=`${data.percentage} %`;$('#level').textContent=level;$('#report').innerHTML=reportRows();$('#analysis').innerHTML=finalAnalysis()}
resetData();progress(0);let caseHTML=paras.map(x=>`<p>${x}</p>`).join('');$('#caseBox').innerHTML=caseHTML;$('#modalCase').innerHTML=caseHTML;$('#start').onclick=()=>{let n=$('#student').value.trim();if(n.length<3){$('#nameError').textContent='Escribe un nombre de al menos 3 caracteres.';$('#student').focus();return}data.name=n;$('#nameError').textContent='';show('#instructions',0)};$('#student').onkeydown=e=>{if(e.key==='Enter')$('#start').click()};$('#read').onclick=()=>{show('#caseScreen',0);$('#greeting').textContent=`${data.name}, analiza cuidadosamente el siguiente caso.`;$('#caseBox').scrollTop=0;$('#begin').disabled=true};$('#caseBox').onscroll=e=>{let b=e.target;if(b.scrollTop+b.clientHeight>=b.scrollHeight-8){$('#begin').disabled=false;$('#scrollHint').textContent='Lectura completada. Ya puedes comenzar las decisiones.'}};$('#begin').onclick=()=>{index=0;renderQuestion()};$('#confirm').onclick=evaluate;$('#next').onclick=next;$('#validate').onclick=validateMap;$('#seeResults').onclick=results;$('#print').onclick=()=>window.print();$('#restart').onclick=()=>{if(confirm('¿Deseas iniciar una nueva simulación? Se eliminarán los resultados actuales.')){resetData();$('#student').value='';show('#name',0);$('#student').focus()}};$$('.consult').forEach(b=>b.onclick=()=>$('#modal').showModal());$('#close').onclick=()=>$('#modal').close();$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').close()};
})();
